/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sun_glass_ui_monocle_LinuxSystem_FbVarScreenInfo */

#ifndef _Included_com_sun_glass_ui_monocle_LinuxSystem_FbVarScreenInfo
#define _Included_com_sun_glass_ui_monocle_LinuxSystem_FbVarScreenInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sun_glass_ui_monocle_LinuxSystem_FbVarScreenInfo
 * Method:    sizeof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_sun_glass_ui_monocle_LinuxSystem_00024FbVarScreenInfo_sizeof
  (JNIEnv *, jobject);

/*
 * Class:     com_sun_glass_ui_monocle_LinuxSystem_FbVarScreenInfo
 * Method:    getBitsPerPixel
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_sun_glass_ui_monocle_LinuxSystem_00024FbVarScreenInfo_getBitsPerPixel
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_sun_glass_ui_monocle_LinuxSystem_FbVarScreenInfo
 * Method:    getXRes
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_sun_glass_ui_monocle_LinuxSystem_00024FbVarScreenInfo_getXRes
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_sun_glass_ui_monocle_LinuxSystem_FbVarScreenInfo
 * Method:    getYRes
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_sun_glass_ui_monocle_LinuxSystem_00024FbVarScreenInfo_getYRes
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_sun_glass_ui_monocle_LinuxSystem_FbVarScreenInfo
 * Method:    getXResVirtual
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_sun_glass_ui_monocle_LinuxSystem_00024FbVarScreenInfo_getXResVirtual
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_sun_glass_ui_monocle_LinuxSystem_FbVarScreenInfo
 * Method:    getYResVirtual
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_sun_glass_ui_monocle_LinuxSystem_00024FbVarScreenInfo_getYResVirtual
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_sun_glass_ui_monocle_LinuxSystem_FbVarScreenInfo
 * Method:    getOffsetX
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_sun_glass_ui_monocle_LinuxSystem_00024FbVarScreenInfo_getOffsetX
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_sun_glass_ui_monocle_LinuxSystem_FbVarScreenInfo
 * Method:    getOffsetY
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_sun_glass_ui_monocle_LinuxSystem_00024FbVarScreenInfo_getOffsetY
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_sun_glass_ui_monocle_LinuxSystem_FbVarScreenInfo
 * Method:    setRes
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_sun_glass_ui_monocle_LinuxSystem_00024FbVarScreenInfo_setRes
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_sun_glass_ui_monocle_LinuxSystem_FbVarScreenInfo
 * Method:    setVirtualRes
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_sun_glass_ui_monocle_LinuxSystem_00024FbVarScreenInfo_setVirtualRes
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_sun_glass_ui_monocle_LinuxSystem_FbVarScreenInfo
 * Method:    setOffset
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_sun_glass_ui_monocle_LinuxSystem_00024FbVarScreenInfo_setOffset
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_sun_glass_ui_monocle_LinuxSystem_FbVarScreenInfo
 * Method:    setActivate
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_sun_glass_ui_monocle_LinuxSystem_00024FbVarScreenInfo_setActivate
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_sun_glass_ui_monocle_LinuxSystem_FbVarScreenInfo
 * Method:    setBitsPerPixel
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_sun_glass_ui_monocle_LinuxSystem_00024FbVarScreenInfo_setBitsPerPixel
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_sun_glass_ui_monocle_LinuxSystem_FbVarScreenInfo
 * Method:    setRed
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_sun_glass_ui_monocle_LinuxSystem_00024FbVarScreenInfo_setRed
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_sun_glass_ui_monocle_LinuxSystem_FbVarScreenInfo
 * Method:    setGreen
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_sun_glass_ui_monocle_LinuxSystem_00024FbVarScreenInfo_setGreen
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_sun_glass_ui_monocle_LinuxSystem_FbVarScreenInfo
 * Method:    setBlue
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_sun_glass_ui_monocle_LinuxSystem_00024FbVarScreenInfo_setBlue
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_sun_glass_ui_monocle_LinuxSystem_FbVarScreenInfo
 * Method:    setTransp
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_sun_glass_ui_monocle_LinuxSystem_00024FbVarScreenInfo_setTransp
  (JNIEnv *, jobject, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
