/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sun_glass_ui_monocle_Udev */

#ifndef _Included_com_sun_glass_ui_monocle_Udev
#define _Included_com_sun_glass_ui_monocle_Udev
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sun_glass_ui_monocle_Udev
 * Method:    _open
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_sun_glass_ui_monocle_Udev__1open
  (JNIEnv *, jobject);

/*
 * Class:     com_sun_glass_ui_monocle_Udev
 * Method:    _readEvent
 * Signature: (JLjava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_com_sun_glass_ui_monocle_Udev__1readEvent
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_sun_glass_ui_monocle_Udev
 * Method:    _close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_sun_glass_ui_monocle_Udev__1close
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_sun_glass_ui_monocle_Udev
 * Method:    _getPropertiesOffset
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_com_sun_glass_ui_monocle_Udev__1getPropertiesOffset
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_sun_glass_ui_monocle_Udev
 * Method:    _getPropertiesLength
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_com_sun_glass_ui_monocle_Udev__1getPropertiesLength
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
