/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sun_glass_ui_monocle_C_Structure */

#ifndef _Included_com_sun_glass_ui_monocle_C_Structure
#define _Included_com_sun_glass_ui_monocle_C_Structure
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
