/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sun_glass_ui_monocle_X_XColor */

#ifndef _Included_com_sun_glass_ui_monocle_X_XColor
#define _Included_com_sun_glass_ui_monocle_X_XColor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sun_glass_ui_monocle_X_XColor
 * Method:    setRed
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_sun_glass_ui_monocle_X_00024XColor_setRed
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_sun_glass_ui_monocle_X_XColor
 * Method:    setGreen
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_sun_glass_ui_monocle_X_00024XColor_setGreen
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_sun_glass_ui_monocle_X_XColor
 * Method:    setBlue
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_sun_glass_ui_monocle_X_00024XColor_setBlue
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_sun_glass_ui_monocle_X_XColor
 * Method:    sizeof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_sun_glass_ui_monocle_X_00024XColor_sizeof
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
