/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sun_glass_ui_monocle_LinuxSystem_InputAbsInfo */

#ifndef _Included_com_sun_glass_ui_monocle_LinuxSystem_InputAbsInfo
#define _Included_com_sun_glass_ui_monocle_LinuxSystem_InputAbsInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sun_glass_ui_monocle_LinuxSystem_InputAbsInfo
 * Method:    sizeof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_sun_glass_ui_monocle_LinuxSystem_00024InputAbsInfo_sizeof
  (JNIEnv *, jobject);

/*
 * Class:     com_sun_glass_ui_monocle_LinuxSystem_InputAbsInfo
 * Method:    getValue
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_sun_glass_ui_monocle_LinuxSystem_00024InputAbsInfo_getValue
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_sun_glass_ui_monocle_LinuxSystem_InputAbsInfo
 * Method:    getMinimum
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_sun_glass_ui_monocle_LinuxSystem_00024InputAbsInfo_getMinimum
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_sun_glass_ui_monocle_LinuxSystem_InputAbsInfo
 * Method:    getMaximum
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_sun_glass_ui_monocle_LinuxSystem_00024InputAbsInfo_getMaximum
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_sun_glass_ui_monocle_LinuxSystem_InputAbsInfo
 * Method:    getFuzz
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_sun_glass_ui_monocle_LinuxSystem_00024InputAbsInfo_getFuzz
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_sun_glass_ui_monocle_LinuxSystem_InputAbsInfo
 * Method:    getFlat
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_sun_glass_ui_monocle_LinuxSystem_00024InputAbsInfo_getFlat
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_sun_glass_ui_monocle_LinuxSystem_InputAbsInfo
 * Method:    getResolution
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_sun_glass_ui_monocle_LinuxSystem_00024InputAbsInfo_getResolution
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
