/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sun_glass_ui_monocle_X_XDisplay */

#ifndef _Included_com_sun_glass_ui_monocle_X_XDisplay
#define _Included_com_sun_glass_ui_monocle_X_XDisplay
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sun_glass_ui_monocle_X_XDisplay
 * Method:    sizeof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_sun_glass_ui_monocle_X_00024XDisplay_sizeof
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
