/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sun_glass_ui_monocle_X_XButtonEvent */

#ifndef _Included_com_sun_glass_ui_monocle_X_XButtonEvent
#define _Included_com_sun_glass_ui_monocle_X_XButtonEvent
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sun_glass_ui_monocle_X_XButtonEvent
 * Method:    getButton
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_sun_glass_ui_monocle_X_00024XButtonEvent_getButton
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
