/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sun_glass_ui_monocle_X_XEvent */

#ifndef _Included_com_sun_glass_ui_monocle_X_XEvent
#define _Included_com_sun_glass_ui_monocle_X_XEvent
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sun_glass_ui_monocle_X_XEvent
 * Method:    sizeof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_sun_glass_ui_monocle_X_00024XEvent_sizeof
  (JNIEnv *, jobject);

/*
 * Class:     com_sun_glass_ui_monocle_X_XEvent
 * Method:    getType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_sun_glass_ui_monocle_X_00024XEvent_getType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_sun_glass_ui_monocle_X_XEvent
 * Method:    getWindow
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_sun_glass_ui_monocle_X_00024XEvent_getWindow
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_sun_glass_ui_monocle_X_XEvent
 * Method:    setWindow
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_sun_glass_ui_monocle_X_00024XEvent_setWindow
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
