/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sun_glass_ui_monocle_LinuxSystem */

#ifndef _Included_com_sun_glass_ui_monocle_LinuxSystem
#define _Included_com_sun_glass_ui_monocle_LinuxSystem
#ifdef __cplusplus
extern "C" {
#endif
#undef com_sun_glass_ui_monocle_LinuxSystem_O_RDONLY
#define com_sun_glass_ui_monocle_LinuxSystem_O_RDONLY 0L
#undef com_sun_glass_ui_monocle_LinuxSystem_O_WRONLY
#define com_sun_glass_ui_monocle_LinuxSystem_O_WRONLY 1L
#undef com_sun_glass_ui_monocle_LinuxSystem_O_RDWR
#define com_sun_glass_ui_monocle_LinuxSystem_O_RDWR 2L
#undef com_sun_glass_ui_monocle_LinuxSystem_O_NONBLOCK
#define com_sun_glass_ui_monocle_LinuxSystem_O_NONBLOCK 2048L
#undef com_sun_glass_ui_monocle_LinuxSystem_SEEK_SET
#define com_sun_glass_ui_monocle_LinuxSystem_SEEK_SET 0L
#undef com_sun_glass_ui_monocle_LinuxSystem__SC_LONG_BIT
#define com_sun_glass_ui_monocle_LinuxSystem__SC_LONG_BIT 106L
#undef com_sun_glass_ui_monocle_LinuxSystem_FBIOGET_VSCREENINFO
#define com_sun_glass_ui_monocle_LinuxSystem_FBIOGET_VSCREENINFO 17920L
#undef com_sun_glass_ui_monocle_LinuxSystem_FBIOPUT_VSCREENINFO
#define com_sun_glass_ui_monocle_LinuxSystem_FBIOPUT_VSCREENINFO 17921L
#undef com_sun_glass_ui_monocle_LinuxSystem_FBIOPAN_DISPLAY
#define com_sun_glass_ui_monocle_LinuxSystem_FBIOPAN_DISPLAY 17926L
#undef com_sun_glass_ui_monocle_LinuxSystem_FBIOBLANK
#define com_sun_glass_ui_monocle_LinuxSystem_FBIOBLANK 17937L
#undef com_sun_glass_ui_monocle_LinuxSystem_FB_BLANK_UNBLANK
#define com_sun_glass_ui_monocle_LinuxSystem_FB_BLANK_UNBLANK 0L
#undef com_sun_glass_ui_monocle_LinuxSystem_FB_ACTIVATE_NOW
#define com_sun_glass_ui_monocle_LinuxSystem_FB_ACTIVATE_NOW 0L
#undef com_sun_glass_ui_monocle_LinuxSystem_FB_ACTIVATE_VBL
#define com_sun_glass_ui_monocle_LinuxSystem_FB_ACTIVATE_VBL 16L
#undef com_sun_glass_ui_monocle_LinuxSystem_ENXIO
#define com_sun_glass_ui_monocle_LinuxSystem_ENXIO 6L
#undef com_sun_glass_ui_monocle_LinuxSystem_EAGAIN
#define com_sun_glass_ui_monocle_LinuxSystem_EAGAIN 11L
#undef com_sun_glass_ui_monocle_LinuxSystem_RTLD_LAZY
#define com_sun_glass_ui_monocle_LinuxSystem_RTLD_LAZY 1L
#undef com_sun_glass_ui_monocle_LinuxSystem_RTLD_GLOBAL
#define com_sun_glass_ui_monocle_LinuxSystem_RTLD_GLOBAL 256L
#undef com_sun_glass_ui_monocle_LinuxSystem_PROT_READ
#define com_sun_glass_ui_monocle_LinuxSystem_PROT_READ 1LL
#undef com_sun_glass_ui_monocle_LinuxSystem_PROT_WRITE
#define com_sun_glass_ui_monocle_LinuxSystem_PROT_WRITE 2LL
#undef com_sun_glass_ui_monocle_LinuxSystem_MAP_PRIVATE
#define com_sun_glass_ui_monocle_LinuxSystem_MAP_PRIVATE 2LL
#undef com_sun_glass_ui_monocle_LinuxSystem_MAP_ANONYMOUS
#define com_sun_glass_ui_monocle_LinuxSystem_MAP_ANONYMOUS 32LL
#undef com_sun_glass_ui_monocle_LinuxSystem_MAP_SHARED
#define com_sun_glass_ui_monocle_LinuxSystem_MAP_SHARED 1LL
#undef com_sun_glass_ui_monocle_LinuxSystem_MAP_FAILED
#define com_sun_glass_ui_monocle_LinuxSystem_MAP_FAILED 4294967295LL
/*
 * Class:     com_sun_glass_ui_monocle_LinuxSystem
 * Method:    setenv
 * Signature: (Ljava/lang/String;Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_sun_glass_ui_monocle_LinuxSystem_setenv
  (JNIEnv *, jobject, jstring, jstring, jboolean);

/*
 * Class:     com_sun_glass_ui_monocle_LinuxSystem
 * Method:    open
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_com_sun_glass_ui_monocle_LinuxSystem_open
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_sun_glass_ui_monocle_LinuxSystem
 * Method:    close
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_sun_glass_ui_monocle_LinuxSystem_close
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_sun_glass_ui_monocle_LinuxSystem
 * Method:    lseek
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_com_sun_glass_ui_monocle_LinuxSystem_lseek
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     com_sun_glass_ui_monocle_LinuxSystem
 * Method:    write
 * Signature: (JLjava/nio/ByteBuffer;II)J
 */
JNIEXPORT jlong JNICALL Java_com_sun_glass_ui_monocle_LinuxSystem_write
  (JNIEnv *, jobject, jlong, jobject, jint, jint);

/*
 * Class:     com_sun_glass_ui_monocle_LinuxSystem
 * Method:    read
 * Signature: (JLjava/nio/ByteBuffer;II)J
 */
JNIEXPORT jlong JNICALL Java_com_sun_glass_ui_monocle_LinuxSystem_read
  (JNIEnv *, jobject, jlong, jobject, jint, jint);

/*
 * Class:     com_sun_glass_ui_monocle_LinuxSystem
 * Method:    sysconf
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_sun_glass_ui_monocle_LinuxSystem_sysconf
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_sun_glass_ui_monocle_LinuxSystem
 * Method:    EVIOCGABS
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_sun_glass_ui_monocle_LinuxSystem_EVIOCGABS
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_sun_glass_ui_monocle_LinuxSystem
 * Method:    ioctl
 * Signature: (JIJ)I
 */
JNIEXPORT jint JNICALL Java_com_sun_glass_ui_monocle_LinuxSystem_ioctl
  (JNIEnv *, jobject, jlong, jint, jlong);

/*
 * Class:     com_sun_glass_ui_monocle_LinuxSystem
 * Method:    IOW
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_sun_glass_ui_monocle_LinuxSystem_IOW
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_sun_glass_ui_monocle_LinuxSystem
 * Method:    IOR
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_sun_glass_ui_monocle_LinuxSystem_IOR
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_sun_glass_ui_monocle_LinuxSystem
 * Method:    IOWR
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_sun_glass_ui_monocle_LinuxSystem_IOWR
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_sun_glass_ui_monocle_LinuxSystem
 * Method:    errno
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_sun_glass_ui_monocle_LinuxSystem_errno
  (JNIEnv *, jobject);

/*
 * Class:     com_sun_glass_ui_monocle_LinuxSystem
 * Method:    strerror
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sun_glass_ui_monocle_LinuxSystem_strerror
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_sun_glass_ui_monocle_LinuxSystem
 * Method:    dlopen
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_com_sun_glass_ui_monocle_LinuxSystem_dlopen
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_sun_glass_ui_monocle_LinuxSystem
 * Method:    dlerror
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sun_glass_ui_monocle_LinuxSystem_dlerror
  (JNIEnv *, jobject);

/*
 * Class:     com_sun_glass_ui_monocle_LinuxSystem
 * Method:    dlsym
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_sun_glass_ui_monocle_LinuxSystem_dlsym
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_sun_glass_ui_monocle_LinuxSystem
 * Method:    dlclose
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_sun_glass_ui_monocle_LinuxSystem_dlclose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_sun_glass_ui_monocle_LinuxSystem
 * Method:    mmap
 * Signature: (JJJJJJ)J
 */
JNIEXPORT jlong JNICALL Java_com_sun_glass_ui_monocle_LinuxSystem_mmap
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     com_sun_glass_ui_monocle_LinuxSystem
 * Method:    munmap
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_sun_glass_ui_monocle_LinuxSystem_munmap
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_sun_glass_ui_monocle_LinuxSystem
 * Method:    memcpy
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_com_sun_glass_ui_monocle_LinuxSystem_memcpy
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_sun_glass_ui_monocle_LinuxSystem
 * Method:    mkfifo
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_sun_glass_ui_monocle_LinuxSystem_mkfifo
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
