/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sun_glass_ui_monocle_X_XSetWindowAttributes */

#ifndef _Included_com_sun_glass_ui_monocle_X_XSetWindowAttributes
#define _Included_com_sun_glass_ui_monocle_X_XSetWindowAttributes
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sun_glass_ui_monocle_X_XSetWindowAttributes
 * Method:    sizeof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_sun_glass_ui_monocle_X_00024XSetWindowAttributes_sizeof
  (JNIEnv *, jobject);

/*
 * Class:     com_sun_glass_ui_monocle_X_XSetWindowAttributes
 * Method:    setEventMask
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_sun_glass_ui_monocle_X_00024XSetWindowAttributes_setEventMask
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_sun_glass_ui_monocle_X_XSetWindowAttributes
 * Method:    setCursor
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_sun_glass_ui_monocle_X_00024XSetWindowAttributes_setCursor
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_sun_glass_ui_monocle_X_XSetWindowAttributes
 * Method:    setOverrideRedirect
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_sun_glass_ui_monocle_X_00024XSetWindowAttributes_setOverrideRedirect
  (JNIEnv *, jclass, jlong, jboolean);

#ifdef __cplusplus
}
#endif
#endif
