/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sun_glass_ui_monocle_MX6AcceleratedScreen */

#ifndef _Included_com_sun_glass_ui_monocle_MX6AcceleratedScreen
#define _Included_com_sun_glass_ui_monocle_MX6AcceleratedScreen
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sun_glass_ui_monocle_MX6AcceleratedScreen
 * Method:    _platformGetNativeWindow
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_sun_glass_ui_monocle_MX6AcceleratedScreen__1platformGetNativeWindow
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_sun_glass_ui_monocle_MX6AcceleratedScreen
 * Method:    _platformGetNativeDisplay
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_sun_glass_ui_monocle_MX6AcceleratedScreen__1platformGetNativeDisplay
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
