/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sun_glass_ui_monocle_X_XMotionEvent */

#ifndef _Included_com_sun_glass_ui_monocle_X_XMotionEvent
#define _Included_com_sun_glass_ui_monocle_X_XMotionEvent
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sun_glass_ui_monocle_X_XMotionEvent
 * Method:    getX
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_sun_glass_ui_monocle_X_00024XMotionEvent_getX
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_sun_glass_ui_monocle_X_XMotionEvent
 * Method:    getY
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_sun_glass_ui_monocle_X_00024XMotionEvent_getY
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
