/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sun_glass_ui_monocle_C */

#ifndef _Included_com_sun_glass_ui_monocle_C
#define _Included_com_sun_glass_ui_monocle_C
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sun_glass_ui_monocle_C
 * Method:    NewDirectByteBuffer
 * Signature: (JI)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_sun_glass_ui_monocle_C_NewDirectByteBuffer
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_sun_glass_ui_monocle_C
 * Method:    GetDirectBufferAddress
 * Signature: (Ljava/nio/ByteBuffer;)J
 */
JNIEXPORT jlong JNICALL Java_com_sun_glass_ui_monocle_C_GetDirectBufferAddress
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
