/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sun_glass_ui_monocle_X_XClientMessageEvent */

#ifndef _Included_com_sun_glass_ui_monocle_X_XClientMessageEvent
#define _Included_com_sun_glass_ui_monocle_X_XClientMessageEvent
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sun_glass_ui_monocle_X_XClientMessageEvent
 * Method:    setMessageType
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_sun_glass_ui_monocle_X_00024XClientMessageEvent_setMessageType
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_sun_glass_ui_monocle_X_XClientMessageEvent
 * Method:    setFormat
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_sun_glass_ui_monocle_X_00024XClientMessageEvent_setFormat
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_sun_glass_ui_monocle_X_XClientMessageEvent
 * Method:    setDataLong
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_com_sun_glass_ui_monocle_X_00024XClientMessageEvent_setDataLong
  (JNIEnv *, jclass, jlong, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
